### ISSUE TITLE
[BUG?] - Search Bar is not working

### ISSUE THREAD

**Issue by kamfretoz** [fooyin/fooyin#109]
Using search bar to search on the library or the playlist view doesn't seem to do anything. There's also a chance that i misunderstood of how the search works so please do let me know! 😅

Preview:

https://github.com/ludouzi/fooyin/assets/14798312/7473b0d7-265a-4daa-b38e-3a3a85096695

**Comment by ludouzi** [comment]
I should probably put this in a wiki somewhere 😁

The search bar needs to be connected to widgets to be able to search them. If you click the burger menu (far right button in the search bar), there's an option to "Manage Connections" and connect that search bar to widgets.

However, search functionality is only implemented for the filters and library tree so far. I'm still working on the details of how searching the playlist is going to work, but it'll be done soon.

**Comment by kamfretoz** [comment]
Yup that does it! Thank you for the tips 😁
This will do for now.
