### ISSUE TITLE
How do i edit layouts? Rightclick not working

### ISSUE THREAD

**Issue by illnesse** [fooyin/fooyin#111]
I've been trying for a while to figure out how to edit layouts, after looking at the source i realized that somehow rightclick isn't working for me, i'm  in edit mode but if i rightclick i only get the context  menu of the widgets under the cursor.

fooyin-git from aur

**Comment by ludouzi** [comment]
Layout editing works by editing the widget under the cursor (and it's splitter parent if it has one).  Like this:

[editing.webm](https://github.com/ludouzi/fooyin/assets/45490980/b5bdf4ff-396c-493d-85c8-b9cfa0b6cbf3)

Is your context menu similar to this (along with the overlay)?

**Comment by ludouzi** [comment]
Yeah, there's definitely something wrong there. Just out of interest, does it work if you close the Quick Setup dialog first?

**Comment by ludouzi** [comment]
Thanks. Looks like it's only an issue with Qt 6.7.1. I'll need to do some testing.

**Comment by ludouzi** [comment]
I've made changes to accommodate Qt6.7.1 in https://github.com/ludouzi/fooyin/commit/ed5694ec4207cb8b7c8060cf9d9073979f17313d. It'll be great if you could test it to make sure it fixes things.

**Comment by ludouzi** [comment]
Oh yeah, they use the same method to detect the widget under the mouse. It'll be fixed in a bit.
