### ISSUE TITLE
Help/Feature : Ratings Column

### ISSUE THREAD

**Issue by Alex9001** [fooyin/fooyin#113]
In Foobar2000 and DeadBeeF I have a column with ratings for songs. The ratings are meta tag with RATING and VALUE 1-5

In Foobar2000 the code looks like this:

` $pad($repeat(●,%rating%), 5,o)`

In DeadBeeF the code looks like this:

`$ifequal([%rating%], 5,★★★★★,)$ifequal([%rating%], 4,★★★★,)$ifequal([%rating%], 3,★★★,)$ifequal([%rating%], 2,★★,)$ifequal([%rating%], 1,★,)`

What do I need to write to have this data show in Fooyin?

**Comment by ludouzi** [comment]
I've just added the repeat function so it should be the same as foobar2000:

`$pad($repeat(●,%rating%), 5,o)`

**Comment by ludouzi** [comment]
Forget my earlier comment. It's ``$pad($repeat(●,%%rating%%), 5,o)`` until I've improved parsing of custom tags.

**Comment by Alex9001** [comment]
> Forget my earlier comment. It's `$pad($repeat(●,%%rating%%), 5,o)` until I've improved parsing of custom tags.

Thank you for the quick fix. I can confirm it works if I make a RATINGS field in Fooyin. But if I load a file that's already tagged with a RATINGS field it does not display said field in Fooyin. See #115

**Comment by ludouzi** [comment]
Following the resolution of https://github.com/fooyin/fooyin/issues/115, a rating column can be made using:

`$pad($repeat(●,%rating%), 5, )`.
