### ISSUE TITLE
Feature request - capability to scan replaygain and write to metadate

### ISSUE THREAD

**Issue by Lakis01** [fooyin/fooyin#129]
I appreciate that this is probably quite low on the priority list, but this was what I primarily used foobar for

**Comment by diizzyy** [comment]
Might want to look at https://github.com/cyanreg/cyanrip as it uses ffmpeg for this functionality

**Comment by ludouzi** [comment]
This has now been implemented and will be included in the v0.8.0 release.

**Comment by diizzyy** [comment]
Great, thanks for all your hard work!

**Comment by Lakis01** [comment]
Yes, thank you for the very active development :)
