### ISSUE TITLE
Crash when adding files/directories?

### ISSUE THREAD

**Issue by Unnepad** [fooyin/fooyin#135]
I noticed a problem the first time I tried this player.

For some reason, the player just crashes when loading a file or directory within the application. This also happens if the player was started from the terminal.

This is fixed if the tray icon is enabled (although if you load a directory and then disable the tray icon, it also crashes). I don't know why, but I guess that prevents the program from exiting.

**Comment by ludouzi** [comment]
What OS/DE are you using? Did you install fooyin via a package?

**Comment by Unnepad** [comment]
Yes, I installed the .rpm package from this repository. I'm on Fedora 40.

**Comment by ludouzi** [comment]
Thanks, I'm going to try and reproduce this. 

Something that may help in the meantime is to try installing from the COPR repo [here](https://copr.fedorainfracloud.org/coprs/eclipseo/fooyin/). If that works fine, it's likely a problem with the packaging.

**Comment by Unnepad** [comment]
I also tried that after looking here, but it seems that still happens. It's definitely something related to the package.

**Comment by ludouzi** [comment]
I can't reproduce this on a fresh install of Fedora 40 (Plasma). Does it give any useful terminal output when it crashes?

**Comment by Unnepad** [comment]
For some reason, no, it doesn't leave any error message. Plasma doesn't detects it too.

I'm realising that it's actually the fault of the file picker. Even clicking cancel will cause the program to quit.

I will leave a record if that helps. Maybe there's a debug option or something?
[bug.webm](https://github.com/ludouzi/fooyin/assets/169686846/9ecd2d3b-cfc9-4a6c-b0ba-c3551450e2f9)

**Comment by ludouzi** [comment]
Thanks for the video. It looks like fooyin isn't actually crashing but quitting when the file dialog finishes; that helps narrow it down. 

What version of Qt do you have installed?

**Comment by Unnepad** [comment]
I don't know how to find that.
What commands should I use?

**Comment by ludouzi** [comment]
For KDE it should be `System Settings->System->About this System`

**Comment by Unnepad** [comment]
Oh, right. It's version 6.7.1

**Comment by ludouzi** [comment]
Alright, I've managed to reproduce it using the same Qt version. Working on a fix.

**Comment by ludouzi** [comment]
Looks like this is related to this regression: https://bugreports.qt.io/browse/QTBUG-124386.

I'll test to see if it's resolved using Qt 6.7.2.

**Comment by Unnepad** [comment]
Ouch :disappointed: So it is actually a bug from the Qt engine itself.
At least there's the workaround I mentioned previously, so it shouldn't be a problem for now.

Btw, this is actually a nice Qt player, specially for being modular and straightforward. The others (Audacious, Qmmp) are somewhat less polished and optimized.

**Comment by ludouzi** [comment]
As Qt 6.7.2 is available for Fedora 40, I'll consider this resolved.
