### ISSUE TITLE
Embedded cuesheet is not supported in flac

### ISSUE THREAD

**Issue by zelenin** [fooyin/fooyin#143]
embedded cuesheet in flac supported by foobar2000 is not supported. There is no splitting into tracks. Similarly in m4a

Fooyin:
![fooyin](https://github.com/fooyin/fooyin/assets/1427885/92133ae5-88c8-4d6d-802f-913ba2f7ad10)
Foobar2000:
![foobar2000](https://github.com/fooyin/fooyin/assets/1427885/04343794-f7d4-48b2-a96a-828e63f4bc66)

**Comment by ludouzi** [comment]
I'm guessing you're not running from source? CUE support will be in release 0.4.6 which I'll be pushing soon.

**Comment by zelenin** [comment]
yes, I used the latest version from Releases. Then Resolved
