### ISSUE TITLE
A scobbler would be awesome

### ISSUE THREAD

**Issue by Phycon01** [fooyin/fooyin#144]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by crse** [comment]
Several scrobbling service:
- Last.fm
- Libre.fm
- Maloja
- ListenBrainz
- Pleroma

[https://github.com/web-scrobbler/web-scrobbler](Web Scrobbler) might be a good reference to start with.

**Comment by Phycon01** [comment]
Yeah, I don't usually listen to music online music. What I'd like is a way to scrobble directly from Fooyin,.

Thanks though :-)

**Comment by ludouzi** [comment]
Seeing as this is quite popular and will not take too long to implement, I'll add it to the planned features for v0.5.3.

**Comment by Phycon01** [comment]
Nice one. Thanks :-)

**Comment by ludouzi** [comment]
I'll close this issue as scrobbling has been implemented for Last.fm and ListenBrainz. I'll look into other services at a later date.

**Comment by cheesetosti** [comment]
Maloja/custom scrobbler URL support would be awesome!
