### ISSUE TITLE
[Feature Request] Double Click for new playtlist, middle click to close playlist

### ISSUE THREAD

**Issue by Alex9001** [fooyin/fooyin#147]
Please implement a feature that user can double click to create new playlist and middle click to close playlist. Like on Foobar.

**Describe the solution you'd like**
When double clicking the empty area to the right of playlist tabs a new playlist to be created. When middle clicking a playlist tab the middle clicked playlist tab closes.

**Comment by ludouzi** [comment]
Done. Middle-clicking to close a playlist can be enabled in Settings->Playlist->Playlist Tabs.

**Comment by Alex9001** [comment]
Not priority, but if you could make the add button smaller at some point that would be cool. Right now its larger than the playlist tabs.

![Screenshot_20240625_170347](https://github.com/fooyin/fooyin/assets/2770710/2c1617c8-52d9-4f8c-bb15-7574ac0fd6c7)
