### ISSUE TITLE
Ability to play music from directly from Library Tree

### ISSUE THREAD

**Issue by talentlessguy** [fooyin/fooyin#148]
Hello, thanks for developing this player. So far it's one of the most well done ones, because honestly many others simply suck.

I'm loving it so far but one thing that I really would like to be implemented is being able to play a song directly from Library Tree:

![image](https://github.com/fooyin/fooyin/assets/35937217/2d32005f-7dd1-4cc6-b343-0aafd2c3e449)

Right now I'm using a file browser but it's not preferrable because I want to have it displayed like library tree.

So, adding a "play" functionality from file browser to the library tree would be super cool

**Comment by ludouzi** [comment]
Thank you!

A tree-based view is also an option for the directory browser in settings:

![Screenshot_20240625_000907](https://github.com/fooyin/fooyin/assets/45490980/657139bd-fa87-41f8-9243-fc29ca5d9b70)

Although it only displays the filesystem structure, so may not be ideal depending on your library.

Adding direct playback support to the library tree wouldn't be too difficult, so I'll look into it in a bit.

**Comment by ludouzi** [comment]
I've just added direct playback support. There's a 'Play' context menu entry, and play on double-click can be enabled on the library tree settings page.

**Comment by talentlessguy** [comment]
Thanks for implementing this! Do you have a date for when this features makes it into a release?

**Comment by ludouzi** [comment]
I still have a few things left to do but aiming to release v0.5.0 by the end of this week.
