### ISSUE TITLE
Playlist Blank

### ISSUE THREAD

**Issue by Alex9001** [fooyin/fooyin#159]
**Describe the bug**
One of the updates in the last few days made it so the playlist doesn't show anything

**To Reproduce**
Install fooyin from AUR fooyin-git on Artix Linux
Try to load files into playlist. Nothing shows. Whether drag/drop or from library

**Expected behaviour**
It should show stuff in the playlist

**Screenshots**

https://github.com/fooyin/fooyin/assets/2770710/3c78c38f-bd6f-4853-a1a8-776ad79b638b

**System:**
 - OS: Artix Linux
 - fooyin version: 0.5.1 from git on 6/29

**Additional context**
It used to work then an update made it not work

**Comment by ludouzi** [comment]
Interesting. Do you have the playlist header set to hidden? If not, can you try removing the playlist in layout editing mode and re-adding it?

**Comment by Alex9001** [comment]
> Interesting. Do you have the playlist header set to hidden? If not, can you try removing the playlist in layout editing mode and re-adding it?

I changed layout mode and that made the playlist work again. Im not sure how to set the header to hidden, right click playlist > presets > ? but you can't hide it from there something must be selected.

anyway i guess this is closed. I don't think I did anything but I could be wrong.

**Comment by ludouzi** [comment]
Thanks. It looks like the header state might have been corrupted (which is saved to the layout), hence why it and the playlist didn't show. I'll see if I can address that in case it happens again.
