### ISSUE TITLE
[Bug] Horizontal Splitter is vertical, Vertical splitter is horizontal

### ISSUE THREAD

**Issue by Alex9001** [fooyin/fooyin#161]
**Describe the bug**
When right click > add splitter > vertical , a horizontal splitter is created
When right click > add splitter > horizontal , a vertical splitter is created

**To Reproduce**
View > layout > empty > right click empty > insert > splitters > vertical/horizontal

**Expected behaviour**
It should be the inverse of what it is

**Screenshots**

https://github.com/fooyin/fooyin/assets/2770710/1b34050d-a0c5-4434-91e2-16cbbd8c4543

![Screenshot_20240630_045231](https://github.com/fooyin/fooyin/assets/2770710/db650ec1-ef72-42e5-8724-167e9d56453a)

**System:**
 - OS: Artix Linux
 - fooyin version: 0.5.1

**Additional context**
Horizon goes side to side

**Comment by ludouzi** [comment]
The splitters were originally named based on the underlying QSplitter orientation:

>  A default QSplitter lays out its children horizontally (side by side); you can use [setOrientation](https://doc.qt.io/qt-6/qsplitter.html#orientation-prop)([Qt::Vertical](https://doc.qt.io/qt-6/qt.html#Orientation-enum)) to lay its children out vertically.

But I can see why that might be confusing to some. I'll think of more descriptive names for them both.
