### ISSUE TITLE
[Bug] Adding Widgets is Inverted

### ISSUE THREAD

**Issue by Alex9001** [fooyin/fooyin#162]
**Describe the bug**
If I have a horizontal split in the interface, and I click to add a widget to the left side, it adds a widget to the right side. And vice versa.

**To Reproduce**
view>layout>empty

make a vertical splitter, click left side, add any widget, it adds to right side.

**Expected behaviour**
If I click to add a widget the widget should be added to the place I clicked

**Screenshots**

https://github.com/fooyin/fooyin/assets/2770710/fb034a19-ae61-4746-8389-391456f5d84c

**System:**
 - OS: Artix Linux
 - fooyin version: 0.5.1

**Comment by ludouzi** [comment]
The layout editing menu has two levels: 

1.  Widget under the cursor
1.  Container/splitter of the above widget

If you were to use `Widget->Insert` in the menu, it would add it to the place under the cursor. The bottom section of the menu is for the splitter, and it always adds to the right of the widget under the cursor.

To make this clearer, perhaps the splitter section of the layout editing menu shouldn't be shown if clicking one of the two initial placeholders.
