### ISSUE TITLE
Updated, will not run.

### ISSUE THREAD

**Issue by xircon** [fooyin/fooyin#164]
**Describe the bug**
```
Skipping loading of translations for locale "en_GB"
malloc(): unaligned tcache chunk detected
fish: Job 1, 'fooyin' terminated by signal SIGABRT (Abort)
```

**To Reproduce**
Steps to reproduce the behaviour.
Updated to 0.5.1-1, will not start.

**Expected behaviour**
Not crash

**Screenshots**

**System:**
 - OS: EndeavourOS
 - fooyin version: 0.5.1-1

**Additional context**

**Comment by ludouzi** [comment]
I suspect this may be related to https://github.com/fooyin/fooyin/issues/163. Once I've confirmed that's fixed, I'll push another bugfix release.

**Comment by ludouzi** [comment]
As there haven't been any further updates to this, I'll consider it resolved.
