### ISSUE TITLE
Crash when $pad is used with empty 3rd argument

### ISSUE THREAD

**Issue by Tarvan** [fooyin/fooyin#167]
**Describe the bug**
When the function $pad() is used with empty third argument, the app crashes.

**To Reproduce**
1. Open the Script Sandbox
2. type `$pad(t,10,)`

**Expected behaviour**
Error message or nothing in the result field

**System:**
 - OS: Debian GNU/Linux 12
 - fooyin version: 0.5.1 (.deb package from the releases page)

**Comment by ludouzi** [comment]
Thanks. `$padright` has also been fixed.
