### ISSUE TITLE
[Feature Request] Ability to have the folder structure view in Library Tree follow cursor navigation

### ISSUE THREAD

**Issue by MasterFrag** [fooyin/fooyin#169]
A couple of minor adjustments I'd love to see is the ability to have the folder structure view follow navigation. This may be a niche use case, but I do almost everything involving adding things to my playlist with the arrow keys in Foobar, and thus similarly in Fooyin, and this is something that both Foobar's stock album list, and the Columns UI album list panel does.

Specifically, I've love to see this functionality:

https://github.com/fooyin/fooyin/assets/6836740/406385cc-3a21-4853-aa79-f531d7f20399

In closing, thank you so much for your work, Fooyin is the first audio player that has actually almost met my use case, as almost no other *nix media player can replicate how I use Foobar2000, and I've tried 'em all. Yours is the single best alternative we have, and every update makes it even better.

Edit: A previous version of this request had a feature that I did not previously find regarding font sizes. I just didn't look hard enough, so disregard that.

**Comment by ludouzi** [comment]
Thanks for the request and your kind words.

This should be fairly easy to implement, so I'll have a go now.
