### ISSUE TITLE
APE playback is broken

### ISSUE THREAD

**Issue by Pathologic** [fooyin/fooyin#173]
**Describe the bug**
One second of the track is played, then some seconds are skipped - so till the end of the track.
I've tried different tracks, standalone and with cue, but no success.

**Expected behaviour**
Smooth playback :smile_cat: 

**System:**
 - OS: Kubuntu 22.04.4 LTS x86_64
 - fooyin version: 0.5.3

Thank you for your work, really nice player.

**Comment by ludouzi** [comment]
Thanks, I can reproduce this. It's one of the few formats that hasn't had much testing yet.

**Comment by ludouzi** [comment]
I've fixed playback of APE files on my end, but I'll leave this issue open until it's confirmed to be resolved.

**Comment by Pathologic** [comment]
It seems to be working now, thank you.
