### ISSUE TITLE
Library tree: Open Containing Folder is not working if there are subfolders

### ISSUE THREAD

**Issue by Pathologic** [fooyin/fooyin#175]
**Describe the bug**
I have the library tree with grouping by folder structure enabled. Open Containing Folder command is working only for folders without subfolders, it's disabled otherwise.

**To Reproduce**
1. Add a folder with subfolders to the library.
2. Open context menu for this folder.
3. Open Containg Folder command will be disabled.

**Expected behaviour**
The command should work for all folders.

**Screenshots**
![image](https://github.com/fooyin/fooyin/assets/3012304/2f364f55-d2c9-46cd-a44b-3245fe0c59cb)

**System:**
 - OS: Kubuntu 22.04.4 LTS x86_64
 - fooyin version: 0.5.3

**Comment by ludouzi** [comment]
Open Containing Folder is only enabled when all of the selected tracks are in the same directory. Selecting a folder in the library tree with subfolders means tracks in different folders are selected, so it's disabled to prevent opening too many windows.

I'll see if I can change this behaviour specifically for the folder structure view.

**Comment by Pathologic** [comment]
> Open Containing Folder is only enabled when all of the selected tracks are in the same directory. Selecting a folder in the library tree with subfolders means tracks in different folders are selected, so it's disabled to prevent opening too many windows.
> 
> I'll see if I can change this behaviour specifically for the folder structure view.

I expect one window to be opened in my example:
![image](https://github.com/fooyin/fooyin/assets/3012304/58494c28-af59-4ea9-b099-1b46faa9cac6)

**Comment by ludouzi** [comment]
Having thought about this, the best way to handle this will be to add a separate menu option - Open Folder. 

Open Containing Folder is designed to open the _containing_ folder of a track selection, and adjusting it for this specific use case will be difficult.

Open Folder can be an option only visible in the folder structure grouping.

**Comment by Pathologic** [comment]
Yes, looks like a good solution.
