### ISSUE TITLE
Wrong tracks order

### ISSUE THREAD

**Issue by Pathologic** [fooyin/fooyin#178]
**Describe the bug**
The tracks are sorted by the track number only: 1st track from one CD, then 1st track from another CD and so on.

**Expected behaviour**
There should be tracks from CD 1, then from CD 2.

**Screenshots**
Current behavior:
![image](https://github.com/fooyin/fooyin/assets/3012304/b10066a9-2812-4dbc-82f5-4d348fd05133)

Expected behaviour:
![image](https://github.com/fooyin/fooyin/assets/3012304/2c114542-a6ee-43ce-8bd5-efbdb6388eeb)

**System:**
 - OS: Kubuntu 22.04.4 LTS x86_64
 - fooyin version: 0.5.3

**Additional context**
Deadbeef and Foobar play this album correctly. I've attached cue sheets just in case.
[Ataraxia - Spams - CD 1.cue.txt](https://github.com/user-attachments/files/16149502/Ataraxia.-.Spams.-.CD.1.cue.txt)
[Ataraxia - Spams - CD 2.cue.txt](https://github.com/user-attachments/files/16149503/Ataraxia.-.Spams.-.CD.2.cue.txt)

**Comment by Pathologic** [comment]
Another case: CD 2 appears before CD 1 in the playlist.
![image](https://github.com/fooyin/fooyin/assets/3012304/31343fe3-4263-4878-9eef-6372334f32e5)

[Walk Into My Open Womb - Chapter 2.cue.txt](https://github.com/user-attachments/files/16149616/Walk.Into.My.Open.Womb.-.Chapter.2.cue.txt)
[Walk Into My Open Womb - Disc 1.cue.txt](https://github.com/user-attachments/files/16149617/Walk.Into.My.Open.Womb.-.Disc.1.cue.txt)

**Comment by Pathologic** [comment]
It seems that tracks are sorted by Artist/Album, not by the track number.

**Comment by ludouzi** [comment]
Yeah, it's the sort script in `Settings->Library->Sorting->Sort tracks in library by`. Removing it preserves the tracks original order. The lack of a disc number causes the problem in the first example. I'll look into the second. 

Removing `$num(%track%,5) - %title%` from the end should fix it, though this may cause issues with sorting elsewhere, so I'll do some testing on this later.

**Comment by Pathologic** [comment]
Removing value from the sorting settings helped in all of my cases. So it seems to be mostly a feature then a bug.

**Comment by Pathologic** [comment]
Another case: the first track is Track 13. 

Also this album has m3u playlist, but Track 13 from m3u isn't added to the playlist at all.

[Mylene Farmer - Innamoramento.cue.txt](https://github.com/user-attachments/files/16180905/Mylene.Farmer.-.Innamoramento.cue.txt)
[Mylene Farmer - Innamoramento.m3u.txt](https://github.com/user-attachments/files/16180906/Mylene.Farmer.-.Innamoramento.m3u.txt)

**Comment by ludouzi** [comment]
Thanks for all those cue files; I found and fixed several issues in their parsing.

**Comment by Pathologic** [comment]
One more сue that fails in fooyin:
[Peter Bjargo - The Translucency Of Mind’s Decay.cue.txt](https://github.com/user-attachments/files/16183712/Peter.Bjargo.-.The.Translucency.Of.Mind.s.Decay.cue.txt)

**Comment by Pathologic** [comment]
As the problem of tracks order seems to be solved, I'll close this issue and create another one about not working cues.

**Comment by genderneutralnoun** [comment]
This is still happening to me; I'm not sure how to fix it. I tried removing the bit in the filter script like it was said, but they still show up wrong in the Library Tree panel. Here's a screenshot: 
![image](https://github.com/user-attachments/assets/6a4093c5-b8c9-4ba7-98fa-81f10b8defc9)
