### ISSUE TITLE
Album Artist metadata won't show when there's more than one

### ISSUE THREAD

**Issue by CelestialProvidence** [fooyin/fooyin#179]
**Describe the bug**
On foobar I have some albums with more than one album artist, each separated by semicolons. On fooyin, these albums show as having no album artists at all. There are also issues with genre tags and possibly more.

**To Reproduce**
On foobar2000 in Windows, give a track more than one album artist.
On fooyin in Linux, see that there is no album artist listed.

**Expected behaviour**
The files should show as having multiple album artists, and in the library tree in fooyin each album artist should appear.

**Screenshots**

**System:**
 - OS: Arch Linux
 - fooyin version: 0.5.3-1 (AUR)

**Additional context**
There are also problems when changing metadata. For instance, I went into folder structure view in the library tree to edit an album to have a single album artist (it had no entry before on both foobar2000 in Windows and fooyin in Linux) and this caused the folder to disappear from view until I restarted fooyin. There was also an individual file that had incorrect an album artist tag, and when I tried changing it, it would simply remain the same.

**Comment by ludouzi** [comment]
I'll consider all the mentioned issues resolved as of the latest release.
