### ISSUE TITLE
Track info (Selection info) behaviour

### ISSUE THREAD

**Issue by Pathologic** [fooyin/fooyin#182]
**Describe the bug**
Nominally it's not a bug, as this widget is called Selection info, but the behavior looks a bit strange. I do not expect the widget to be updated when I'm clicking items in the library tree, especially when a track is playing and I see track info in the widget. Besides that, if I want to get some info about the library tree item then I can use Properties command in the library tree context menu, and it looks to be a more convenient way.

**Expected behaviour**
I expect the widget to show info about the current playing or selected track in the playlist, not about selection in the library tree. Maybe another widget is needed just to show current playing track info?

**System:**
 - OS: Kubuntu 22.04.4 LTS x86_64
 - fooyin version: 0.5.3

**Comment by ludouzi** [comment]
I think the best way to handle this would be to add an option similar to the artwork display - prefer selection or prefer playing track. I'll think about more precise control too.

**Comment by Pathologic** [comment]
It works, thanks. I've found another bug: status widget is glitching on update if it has scrollbar.

https://github.com/user-attachments/assets/bb7c0dce-3d84-4afa-a11c-90c51f82c018

**Comment by ludouzi** [comment]
I can't seem to reproduce that using any style but https://github.com/fooyin/fooyin/commit/fda5c4991f86cf5f5789a8209346bb4091dbadde may help.

**Comment by Pathologic** [comment]
> I can't seem to reproduce that using any style but [fda5c49](https://github.com/fooyin/fooyin/commit/fda5c4991f86cf5f5789a8209346bb4091dbadde) may help.

It didn't help, but disabling scrollbar in the widget properties did the trick. The content is still scrollable with mouse wheel.
