### ISSUE TITLE
No %playingicon% output in the playlist column

### ISSUE THREAD

**Issue by Pathologic** [fooyin/fooyin#184]
**Describe the bug**
I've tried to create a custom column to display track number with playing icon:
```
$num(%track%,2) %playingicon%
%track% %playingicon%
```
and some other combinations. The icon is shown only when the column value contains single %playingicon% placeholder.

**System:**
 - OS: Kubuntu 22.04.4 LTS x86_64
 - fooyin version: 0.5.3

**Comment by ludouzi** [comment]
%playingicon% is currently only supported when used by itself in a column. It may be possible to support columns like the above, so I'll look into this.

**Comment by ludouzi** [comment]
Looks like this can be supported:

![image](https://github.com/fooyin/fooyin/assets/45490980/72ba5cf9-5723-4021-a0a1-bbea964ddc04)


The only limitation is %playingicon% can be displayed either left or right of the rest of the column.

**Comment by Pathologic** [comment]
Cool, thank you.

11 июля 2024 г. 12:12:09 GMT+03:00, Luke Taylor ***@***.***> пишет:
