### ISSUE TITLE
Provide Basic Documentation for the Columns Feature within Playlists

### ISSUE THREAD

**Issue by Kraken0666** [fooyin/fooyin#194]
I would like to suggest basic documentation to be provided for the programs columns section, the most I can find is this section of code from `src/gui/playlist/playlistcolumnregistry.cpp`

>void PlaylistColumnRegistry::loadDefaults()
{
    addDefaultItem({.id = 0, .name = tr("Track"), .field = QStringLiteral("[%disc%.]$num(%track%,2)")});
    addDefaultItem({.id = 1, .name = tr("Title"), .field = QStringLiteral("%title%")});
    addDefaultItem({.id = 2, .name = tr("Artist"), .field = QStringLiteral("%artist%")});
    addDefaultItem({.id = 3, .name = tr("Artist/Album"), .field = QStringLiteral("[%albumartist% - ]%album%")});
    addDefaultItem({.id = 4, .name = tr("Album Artist"), .field = QStringLiteral("%albumartist%")});
    addDefaultItem({.id = 5, .name = tr("Album"), .field = QStringLiteral("%album%")});
    addDefaultItem({.id = 7, .name = tr("Duration"), .field = QStringLiteral("%duration%")});
    addDefaultItem({.id = 8, .name = tr("Playing"), .field = QString::fromLatin1(PlayingIcon)});
    addDefaultItem({.id = 9, .name = tr("Codec"), .field = QStringLiteral("%codec%")});
    addDefaultItem({.id = 10, .name = tr("Extension"), .field = QStringLiteral("%extension%")});
    addDefaultItem({.id = 11, .name = tr("Bitrate"), .field = QStringLiteral("%bitrate%")});
    addDefaultItem({.id = 12, .name = tr("Sample Rate"), .field = QStringLiteral("%samplerate%")});
    addDefaultItem({.id = 16, .name = tr("Channels"), .field = QStringLiteral("%channels%")});
    addDefaultItem({.id = 18, .name = tr("Bit Depth"), .field = QStringLiteral("%bitdepth%")});
    addDefaultItem({.id = 17, .name = tr("Last Modified"), .field = QStringLiteral("%lastmodified%")});
    addDefaultItem(
        {.id = 6, .name = tr("Playcount"), .field = QStringLiteral("$ifgreater(%playcount%,0,%playcount%)")});
    addDefaultItem({.id = 19, .name = tr("First Played"), .field = QStringLiteral("%firstplayed%")});
    addDefaultItem({.id = 20, .name = tr("Last Played"), .field = QStringLiteral("%lastplayed%")});
    addDefaultItem({.id = 13, .name = tr("Front Cover"), .field = QString::fromLatin1(FrontCover), .isPixmap = true});
    addDefaultItem({.id = 14, .name = tr("Back Cover"), .field = QString::fromLatin1(BackCover), .isPixmap = true});
    addDefaultItem(
        {.id = 15, .name = tr("Artist Picture"), .field = QString::fromLatin1(ArtistPicture), .isPixmap = true});
}
} // namespace Fooyin`

**Comment by ludouzi** [comment]
Yeah, documentation is something that is currently being worked on. The initial release will cover the basics as well as touch on scripting like the above. I'll have something release soon.

**Comment by 0x0DEADBEE** [comment]
That's great to hear, looking forward to the first revision of the documentation.
