### ISSUE TITLE
[BUG] Adding a folder with an unsupported file adds nothing to playlist

### ISSUE THREAD

**Issue by ManuLinares** [fooyin/fooyin#197]
When I try to drag and drop a folder that contains valid files and 1 invalid one, it doesn't add anything to the playlist.

Expected behaviour: Should skip unsupported files and add the rest of them.

 - OS: Archlinux
 - fooyin version: latest

----
Also, I should create another bug report but, I expect that when pressing *space bar*, the playing start/stops. This corresponds with the intuition of years of players that do this by default, including Spotify.

**Comment by ludouzi** [comment]
I can reproduce this when adding a combination of files and directories. When you say you're running latest, do you mean latest release or from source?

For using space bar for play/pause, you should be able to assign it to the play action under `Settings->Shortcuts->Playback`.

**Comment by ManuLinares** [comment]
> I can reproduce this when adding a combination of files and directories. When you say you're running latest, do you mean latest release or from source?

Latest release aur/fooyin 0.5.3-1 

> For using space bar for play/pause, you should be able to assign it to the play action under `Settings->Shortcuts->Playback`.

Does it pause when adding only "play" shortcut?
Would this be a good default to set?

**Comment by ludouzi** [comment]
> Latest release aur/fooyin 0.5.3-1

A lot of issues with library scanning were recently fixed, so this case may be handled. I'll do some testing with the last release to make sure.

> Does it pause when adding only "play" shortcut?

The 'play' action is really play/pause. I'll see if I can use a more descriptive name in the shortcuts page. It doesn't currently have a default shortcut, so it'd make sense to set one.

**Comment by ManuLinares** [comment]
> A lot of issues with library scanning were recently fixed, so this case may be handled. I'll do some testing with the last release to make sure.

Latest git solves the issue of adding, although after adding a large folder, it scanned, added the files and then a popup with no info was opened, I closed it but I have no info or debug information as to what was that-

Is there a more verbose output from the terminal?

> The 'play' action is really play/pause. I'll see if I can use a more descriptive name in the shortcuts page. It doesn't currently have a default shortcut, so it'd make sense to set one.

The git version apparently removed the "play" shortcut, but the "pause" shorcut has the desired behaviour of play/pause. Thanks

**Comment by ludouzi** [comment]
> a popup with no info was opened

When scanning a large number of files, a modal dialog will open to block input until it's finished. It was most likely that, though it should close automatically when finished. I'll look into it.

> removed the "play" shortcut

The underlying action used for the shortcut text adjusts based on the current playstate - it's 'play' when paused and 'pause' when playing.

**Comment by ManuLinares** [comment]
> The underlying action used for the shortcut text adjusts based on the current playstate - it's 'play' when paused and 'pause' when playing.

Suggestion: Make it static, not dynamic. "play/pause" would suffice

The only feature I would add is a search bar for the playlist to quickly find a song. There is only a search for the Library.

I must say, this is a nice looking codebase.
