### ISSUE TITLE
Search Playlist

### ISSUE THREAD

**Issue by Mordynak** [fooyin/fooyin#199]
Would be nice to have a popup dialogue for searching the current playlist. 
In Foobar2000 this is called by the default keyboard shortcut of F3.
It displays a playlist view with a search filter.

I noticed there is "Query-based language for searching/filtering" in the roadmap. Does this include playlist searching?

**Comment by ludouzi** [comment]
This is something that's been on my to-do list for a while as I was thinking how I would best implement it.

I'm thinking of offering two ways to search:

1. Search dialog which displays filtered tracks and highlights them in the playlist
2. Filter tracks in the playlist directly using a connected search bar

> I noticed there is "Query-based language for searching/filtering" in the roadmap

That refers to being able to search for specific tags and properties like `album=circles` or `playcount>2`. Once that is implemented, it will be used for other features like smart/auto playlists.
