### ISSUE TITLE
Output: ALSA plugin fails to output audio on multiple formats

### ISSUE THREAD

**Issue by diizzyy** [fooyin/fooyin#201]
**Describe the bug**
Working formats: FLAC 44.1Khz, PCM 44.1kHz
Not working: MP4/M4A/AAC 44.1Khz , Opus 44.1kHz, MP3, 44.1kHz (Format not supported: FLOAT_LE)

**To Reproduce**
Play audio files

**Expected behaviour**
Working playback

**Screenshots**
N/A

**System:**
 - OS: FreeBSD 14.1
 - fooyin version:  0.5.3

**Additional context**
FFmpeg 6.1.1
ALSA lib: 1.2.12 (OSS output)

**Comment by ludouzi** [comment]
Is this with a HW device selected? Only bit-perfect playback is supported for now as resampling hasn't been implemented.

**Comment by diizzyy** [comment]
From what I can tell it maps to OSS which in turn uses /dev/dsp* (hw dec)
https://man.freebsd.org/cgi/man.cgi?query=snd&sektion=4
https://wiki.freebsd.org/Sound

fooyin reports the device as "oss - Open Sound System"

**Comment by ludouzi** [comment]
Thanks. This and #200 are likely more to do with OSS than the output plugins themselves. I'll do some testing in a VM.

**Comment by ludouzi** [comment]
Resampling is now implemented for the ALSA driver (and SDL2), though I don't know how it will interact with OSS so it will need some testing.

**Comment by diizzyy** [comment]
All test files works, ALSA does output something interesting though...
```
ALSA: Format not supported: 32 bps
ALSA: Trying all supported formats
ALSA: Found compatible format: 32 bps
```

Thanks for working on this!

**Comment by ludouzi** [comment]
> Thanks for working on this!

No problem!

> ALSA does output something interesting though...

Float samples (32bit) aren't supported by your device but signed 32bit samples are. I'll add the format to that message so it's not confusing.

**Comment by diizzyy** [comment]
Closing report as it works now, thanks!
