### ISSUE TITLE
Save/restore playback state option is working incorrectly

### ISSUE THREAD

**Issue by Pathologic** [fooyin/fooyin#206]
**Describe the bug**
Playback state is not saved correctly.

**To Reproduce**
Set the option on, start playback, then stop and restart fooyin. The last played track will be playing after restart.

**Expected behaviour**
Actual playback state should be kept upon restart.

**Comment by ludouzi** [comment]
After some of the commits I made yesterday, I can't reproduce this again, so it may have had something to do with fading.

**Comment by Pathologic** [comment]
I've compiled https://github.com/fooyin/fooyin/commit/73c7624e761390e3339d28e17ebbd4bcccebcbba and nothing changed.

**Comment by ludouzi** [comment]
What's the value of `Player/LastState` in the config file? (`~/.config/fooyin/fooyin.conf`)

**Comment by Pathologic** [comment]
```
[Player]
ActivePlaylistIndex=1
LastPositon=0
LastState=2
PlayMode=0
SavePlaybackState=true
```

**Comment by ludouzi** [comment]
The stopped state is correctly saved which excludes the most likely cause. I've made changes with https://github.com/fooyin/fooyin/commit/e2afb7c445c1e4d77a35b24cab6d6aa6be5bbbd9 so we only seek if we're restoring a paused/playing state. If nothing changes, then something is starting playback from elsewhere.

**Comment by Pathologic** [comment]
Still doesn't work. Maybe you can add some debug messages to the console on startup?

**Comment by Pathologic** [comment]
So, it logs "App: Restoring playing state…" every time.

**Comment by ludouzi** [comment]
Interesting. If `LastState` in the conf file is 2, then it's casting to the wrong state on load, which is odd. I'll see what I can find out.

**Comment by Pathologic** [comment]
Thank you, now it's fixed.

**Comment by Pathologic** [comment]
I've compiled https://github.com/fooyin/fooyin/commit/b32988508897171c6338c70b77319cb236f5f551 and now playback is silent after restart.

**Comment by Pathologic** [comment]
Thanks.
