### ISSUE TITLE
Replay gain

### ISSUE THREAD

**Issue by freetz13** [fooyin/fooyin#208]
Add support for reading, calculating and applying (Track/Album) Replay Gain

**Comment by diizzyy** [comment]
Already on the roadmap, https://github.com/fooyin/fooyin/blob/master/ROADMAP.md so you can close this request :-)

**Comment by RedSnt** [comment]
Can't wait, it's the one thing that'd make Fooyin a perfect replacement for "that other Windows audio player" in my eyes.

**Comment by freetz13** [comment]
> Already on the roadmap ( https://github.com/fooyin/fooyin/blob/master/ROADMAP.md ) so you can close this request :-)

Ah, sorry, I forgot that already was created similar issue. Yeah, can't wait.

**Comment by freetz13** [comment]
Thank you all, guys, for ReplayGain! Now I can move from Gmusicbrowser to Fooyin completely
