### ISSUE TITLE
Alphanumeric track numbers support

### ISSUE THREAD

**Issue by justjakka** [fooyin/fooyin#209]
I would like to request support for alphanumeric track numbers that are used for vinyl or cassette releases, example:
`1-B1. LOLISTYLE GABBERS — All Is Fair In Love & Sampling.flac` - `[%disc%.]%track%` returns `1.0`

**Comment by ludouzi** [comment]
This will require a database schema change as track numbers are currently stored as integers, but I don't foresee any other issues. In fact, it'd probably be best to store all metadata fields in the database as strings.
