### ISSUE TITLE
External metadata support

### ISSUE THREAD

**Issue by justjakka** [fooyin/fooyin#210]
Would be lovely to see support for external metadata - its currently not being displayed in the metadata field:
![2024-08-04_21-01](https://github.com/user-attachments/assets/7881ae27-a896-4d73-b3f2-0f8e2515420d)

**Comment by ludouzi** [comment]
You mean the extra tags on the right like `ENCODER` under the metadata heading on the left? I'll see about adding it as an option.

**Comment by justjakka** [comment]
yes, the ones that are shown inside angle brackets
