### ISSUE TITLE
[Feature Request] Auto-save fooyin playlists to playlist files in specified location

### ISSUE THREAD

**Issue by genderneutralnoun** [fooyin/fooyin#211]
Hi! I'm really appreciating fooyin; I used to use MusicBee when I was still using Windows and due to various reasons I chose to use a program made for Linux rather than use Wine, and fooyin is the closest I could find. I hope the project continues healthily for a long time.

I use Syncthing to synchronize my music library with my phone. Unfortunately, since it seems like fooyin's playlists are not saved to any sort of standard playlist file format, I have to manually save the files myself to a place that Syncthing will send to my phone. This is manageable while my music library is small and I don't have many playlists, but as my library grows it will become harder and harder. Plus it's also just annoying to have to do it haha. If fooyin could be configured to auto-save files for playlists to a specified location and overwrite said files any time they're changed in fooyin, that would be perfect for my use case.

Thank you in advance for considering my request!

**Comment by ludouzi** [comment]
Thanks for the request! 

fooyin's playlists are stored in the database for performance reasons, but I don't see any issues with providing an option to auto-save to external playlist files as well. This won't take long to implement, so I'll look into it soon.

**Comment by genderneutralnoun** [comment]
Awesome, thank you!
