### ISSUE TITLE
Alphanumeric track number reading is slightly broken

### ISSUE THREAD

**Issue by kode54** [fooyin/fooyin#213]
**Describe the bug**
Since updating, I now experience tracks that have empty totaltracks and/or disc number and/or total discs fields reading those fields as `-1` instead of empty string, so now all my tracks without disc numbers display `-1.05` etc.

**To Reproduce**
1. Install 22c416ee from source using AUR package.
2. Load some tracks with no total tracks and no disc number info.

**Expected behaviour**
Empty track/disc number/total fields should remain as empty string.

**Screenshots**
![image](https://github.com/user-attachments/assets/d7f102f6-1dd7-4d60-8f19-fb4e053bc62e)

**System:**
 - OS: Arch Linux
 - fooyin version: 22c416ee (r2772.22c416ee-1)

**Comment by ludouzi** [comment]
I'll consider this issue resolved with https://github.com/fooyin/fooyin/commit/1ef4c5d3739a156ff23047e57eb7e75678db5abf.
