### ISSUE TITLE
Multiple album artists are displayed with weird symbol inbetween in Selection Info

### ISSUE THREAD

**Issue by lstrsrt** [fooyin/fooyin#216]
(Sorry, I accidentally submitted this report too early, hence the edits.)

Right now, Selection Info shows multiple Album Artists with an empty Unicode square inbetween.

As in:
![Screenshot from 2024-08-09 19-08-32](https://github.com/user-attachments/assets/31a76415-ec66-47eb-a899-cb6b72a892ea)

Another (possible) issue I noticed is that in the main playlist view, artists are normally shown with slashes separating them, but when updating the artists from within Fooyin, they are separated with commas instead. Is this intended?

Screenshot of song with artists updated from within fooyin (displays as separated with commas in fooyin and foobar2000):
![Screenshot from 2024-08-09 19-12-32](https://github.com/user-attachments/assets/f1dff87c-1ea2-49a5-93a0-cf531de37537)

Screenshot of song with artists updated from within foobar2000 (displays as separated with slashes in fooyin, but as separated with commas in foobar2000):
![image](https://github.com/user-attachments/assets/d505faf4-02e3-4f74-b88c-d0b97c003c05)

**Comment by ludouzi** [comment]
Thanks for the noticing the issue with the album artists. That's now fixed with https://github.com/fooyin/fooyin/commit/c128994a02cfef9fffcf4786f1baa70c46cd2984.

For the playlist, I'm guessing it may be parsing the multiple artists as a single artist, since slashes aren't used by fooyin. How are you separating the artists in foobar? With slashes?

**Comment by lstrsrt** [comment]
Yeah, just rebuilt and it's solved, thanks. For the second issue: I always use semicolons in both programs, and in the metadata it's also displayed with semicolons.

I actually just tried updating another song in foobar2000 and this time it's displayed with commas in fooyin, as it should be. I guess this is an old problem that got fixed already, but the fix hasn't "passed over" to previously added songs?

**Comment by ludouzi** [comment]
Yeah, I'm pretty sure all those artists are being seen as a single artist. What format are the files?

**Comment by lstrsrt** [comment]
All mp3 files as far as I can tell.

**Comment by ludouzi** [comment]
Ah, it's probably related to the ID3 version. ID3v2.4 (and sometimes v2.3) uses a null character to separate multiple values but before that it used '/'. I'll see if I can reproduce this.

**Comment by lstrsrt** [comment]
Can confirm this with the mp3tag screenshot below. I manually fixed the third and sixth song from within fooyin, which made it use the v2.4 separators (displayed as two backslashes). The other ones are still on v2.3 and use slashes.

![image](https://github.com/user-attachments/assets/0bc7e5e4-070d-441e-a95e-b5ba3fe724f3)

**Comment by lstrsrt** [comment]
Another problem that came up while narrowing the issue down is that v2.4 artist fields seem to be completely ignored by fooyin. They do not show up in the playlist viewer, and in the properties viewer, the Artist Name field is empty.

**Comment by ludouzi** [comment]
I can't reproduce the v2.4 issue just yet as I don't have many mp3 files but I'll look into it further later.

For v2.3, the library fooyin uses to read tags (TagLib) only splits the artists with a null separator. This is a common problem, as other players also don't handle this from those I've tested. 

We'll probably need to manually split on '/' while making exceptions for common artist names like 'AC/DC'.

**Comment by lstrsrt** [comment]
Looks like the v2.4 issue only occurs when the track has multiple artists.

**Comment by ludouzi** [comment]
Thanks. I've got a few v2.4 files I can test so I'll look into this now.

**Comment by ludouzi** [comment]
Multiple artists separated by '/' are now parsed correctly. I've been unable to reproduce the issue with v2.4 yet.

**Comment by lstrsrt** [comment]
Thanks for the update.
I was also unable to reproduce the v2.4 issue on a fresh install, so I think it was fixed with some earlier commit. I'll close this for now and reopen if it happens again.
