### ISSUE TITLE
Some cues are not parsed

### ISSUE THREAD

**Issue by Pathologic** [fooyin/fooyin#223]
[Путь - Песни смерти.cue.txt](https://github.com/user-attachments/files/16596840/-.cue.txt)
[Шумы России - Бешенство.cue.txt](https://github.com/user-attachments/files/16596841/-.cue.txt)
[Peter.Bjargo.-.The.Translucency.Of.Mind.s.Decay.cue.txt](https://github.com/user-attachments/files/16596842/Peter.Bjargo.-.The.Translucency.Of.Mind.s.Decay.cue.txt)
[Ryr - До конца времён.cue.txt](https://github.com/user-attachments/files/16596843/Ryr.-.cue.txt)

**Comment by ludouzi** [comment]
Thanks, I'll take a look at these. It'd probably be best to add some additional log messages for when files mentioned in cues can't be found too.

**Comment by 23365209** [comment]
I don't know if this and the problem that I have are the same, but I have a couple playlists (.m3u) and I have noticed that some songs that have "special" characters in the /path/to/the/song.mp3 do not get loaded into the playlist panel alongside other songs. ([songs_broken.txt](https://github.com/user-attachments/files/16597493/songs_broken.txt))

**Comment by ludouzi** [comment]
I suspect the two problems may be related. The cues provided by @Pathologic parse fine for me, though there might be an issue with the encoding of the filenames which is why the tracks are not added. I'll look into this.

**Comment by Pathologic** [comment]
Yes, it seems that some characters cause the problem. In [Peter.Bjargo.-.The.Translucency.Of.Mind.s.Decay.cue.txt](https://github.com/user-attachments/files/16596842/Peter.Bjargo.-.The.Translucency.Of.Mind.s.Decay.cue.txt) there's a backtick character, cue is parsed after changing it to the single quotation mark. Though the quotation is displayed incorrectly:
![image](https://github.com/user-attachments/assets/ba0b13c5-2a24-47c5-8dcd-386ae6ad0f10)

**Comment by ludouzi** [comment]
Looks like that file is encoded in Windows-1252, which QStringConverter doesn't support. I'll see if there's a way around it.

**Comment by ludouzi** [comment]
Work is currently in progress to support ICU encodings for QTextStream: https://codereview.qt-project.org/c/qt/qtbase/+/429820.

Until then, we can try using QStringDecoder directly.

**Comment by ludouzi** [comment]
We're now using QStringDecoder which supports most file encodings ICU supports. This requires Qt6.4 and for Qt to be built with ICU support though.

**Comment by Pathologic** [comment]
> Looks like that file is encoded in Windows-1252, which QStringConverter doesn't support. I'll see if there's a way around it.
> 
> Edit: Turns out it does support it if Qt is built with ICU support, but not via QTextStream.

It's windows-1251. Current build is crashed after 2 seconds, but I've seen that tracks are loaded and titles encoding is bad.

**Comment by ludouzi** [comment]
What version of Qt are you using? (`qmake6 --version`)

**Comment by ludouzi** [comment]
Crash should be fixed with https://github.com/fooyin/fooyin/commit/101d8e016425b2abee4901764199769b432925be.

Unfortunately, non-UTF encodings are only supported from Qt6.4 onwards, and it's not really feasible to extend this to older versions.

**Comment by Pathologic** [comment]
Well, it's easier for me to change these cues encoding than to install Qt6.4. 

But still there's something wrong:
![image](https://github.com/user-attachments/assets/af010e3f-3523-4e3f-b069-8e73bcc8827f)
The first track length is incorrect if adding from the library tree. It's correct if I open cue file from the folder.

**Comment by ludouzi** [comment]
I'm guessing that the file was parsed as a single track before cue parsing was fixed. If viewing the library tree in any mode other than 'Folder Structure', it should show the tracks individually. If not, then that's the problem, and I'll need to add options to clean the database for files like those so they can be indexed correctly again.

**Comment by Pathologic** [comment]
I've recreated library. Now these albums disappeared completely.

**Comment by ludouzi** [comment]
Any log messages?

**Comment by Pathologic** [comment]
Anyway, I think the problem is fixed, thanks.
