### ISSUE TITLE
Playback issues with files ripped using "Rip 1.0b"

### ISSUE THREAD

**Issue by therealfumbles** [fooyin/fooyin#224]
I think this might be tag related, but I have a few CDs ripped using this program and they all have playback issues. In most cases they "play" but with no music and the waveform bar is solid blue. In another case the file only plays the last 9 seconds of the file.

If I process the files with "flac -8 original.flac -o new.flac they load and play fine. So it's something to do with how this program either wrote the files or tags (or both?)

Here's a screenshot of the tags for one file. The page on the left is the original file, on the right is the reprocessed file showing more tags. This is also the file that only played the last 9 seconds with the original file.

![Screenshot from 2024-08-14 13-13-37](https://github.com/user-attachments/assets/7c849b8a-2e8a-4adb-8335-0d5db53d8b08)

[Here's a link](https://we.tl/t-32lA6ci6K0) to the file itself

**Comment by ludouzi** [comment]
Looks like Rip is a very old ripper for mac - https://github.com/sbooth/Rip

Thanks for the link. I think you may have uploaded the reprocessed file though, as it shows the full metadata and plays fine. I'll see if I can find any files ripped using Rip as well.

**Comment by ludouzi** [comment]
Hmm. Very odd. What does the details tab look like?

**Comment by therealfumbles** [comment]
Here it is:

![Screenshot from 2024-08-14 14-02-55](https://github.com/user-attachments/assets/59582f26-7026-4b24-9f4c-a66776ca3e78)

**Comment by ludouzi** [comment]
I'm thinking it may be related to TagLib or FFmpeg version differences. 

Which distro are you using?

**Comment by therealfumbles** [comment]
Yeah was thinking the same. I'm on debian sid. Here's what I have installed for taglib and ffmpeg:

libtag1v5/unstable,now 1.13.1-1+b1
libtag1v5-vanilla/unstable,now 1.13.1-1+b1

ffmpeg/unstable,now 7:7.0.2-3
gstreamer1.0-libav/unstable,now 1.24.6-1
harvid/unstable,now 0.9.1-1+b3
libavcodec60/unstable,now 7:6.1.1-5+b1
libavcodec61/unstable,now 7:7.0.2-3
libavdevice61/unstable,now 7:7.0.2-3
libavfilter10/unstable,now 7:7.0.2-3
libavformat60/unstable,now 7:6.1.1-5+b1
libavformat61/unstable,now 7:7.0.2-3
libavutil58/unstable,now 7:6.1.1-5+b1
libavutil59/unstable,now 7:7.0.2-3
libpostproc58/unstable,now 7:7.0.2-3
libswresample4/unstable,now 7:6.1.1-5+b1
libswresample5/unstable,now 7:7.0.2-3
libswscale8/unstable,now 7:7.0.2-3
python3-audioread/unstable,unstable,now 3.0.1-1

**Comment by therealfumbles** [comment]
I tried 6c6fd95 but Sister Ship is still behaving the same with missing tags and only loading the last 9 seconds.

**Comment by Pathologic** [comment]
I've downloaded this file - it's played in fooyin without any troubles.

**Comment by ludouzi** [comment]
I can't reproduce this either on an identical system. 

What sort of drive is mounted at Data2? Is it a local disk?

**Comment by therealfumbles** [comment]
It's a local disk in NTFS format.

I also tried copying the folder to my home Documents folder and dragging it into fooyin just to rule out any NTFS funkiness but it behaves the same.

Very strange that it can't be reproduced. I've mostly focused on this one track but I have maybe a half dozen rips that all act weird, mostly just outputting no audio at all and with a blank waveform.

**Comment by ludouzi** [comment]
Would you mind sharing one of the files which don't play at all?

**Comment by therealfumbles** [comment]
[Here's](https://we.tl/t-ruxGOphlkd) a 3-track single.

Track 1 plays back fine.

Track 2 shows the correct runtime and seems to show a partial waveform but playback starts at exactly one minute before the end of the song.

Track 3 plays no audio and displays a blue bar over a blank waveform.

With singles/albums ripped with this tool it seems as though the first track plays fine and then all subsequent files have issues.

**Comment by ludouzi** [comment]
Thanks. I can reproduce this now - but only if the CUE file is present. Looks like there's still issues parsing multi-file cue sheets.

Could you try adding the files separately without the CUE?

**Comment by therealfumbles** [comment]
That's it! 

I extracted that zip to my docs folder, deleted the cue and log files and dragged the folder into a blank playlist and all three tracks play fine.

I also copied the single that Sister Ship is from to docs and did the same and now it loads and plays the full file.

**Comment by ludouzi** [comment]
Great! I'll see if I can fix parsing those types of cue sheet.

> Would an option to ignore cue files make sense?

Yeah, that definitely makes sense. I'll add an 'exclude file types' option for libraries and dropped files similar to foobar.

**Comment by therealfumbles** [comment]
Thanks for the fix. These are all playing back fine now.
