### ISSUE TITLE
Some tracks do not get loaded correctly in the playlist panel

### ISSUE THREAD

**Issue by 23365209** [fooyin/fooyin#225]
Hey,
Yesterday I made a [comment](https://github.com/fooyin/fooyin/issues/223#issuecomment-2285860800) in an issue that in a couple of my playlists some tracks with "special" characters in the file path weren't being loaded in the playlist panel. Today I installed the `fooyin-git` AUR package to check if my problem was fixed by those commits but it seems that it wasn't the case.

In the meantime, I have managed to make fooyin load those tracks by just opening the .m3u playlist file with a text editor and making one of the tracks that does not get loaded the first line in that file (This works with both the `fooyin` and `fooyin-git` AUR packages).

https://github.com/user-attachments/assets/62bce362-4119-4493-9340-4559ee86b2a9

And here are both playlists: 
[playlist_broken.txt](https://github.com/user-attachments/files/16617629/playlist_broken.txt)
[playlist_fixed.txt](https://github.com/user-attachments/files/16617630/playlist_fixed.txt)

**Comment by ludouzi** [comment]
Thanks for the extra info.

When loading a playlist, we check the first 1024 bytes to determine the file encoding. My first thought is that because there's no unicode characters in the first entry in the broken playlist, it's read as latin-1. I'll do some tests to confirm if this is the case.

**Comment by ludouzi** [comment]
Looks like I was right. UTF-8 is now used if an exact encoding can't be detected, so this should be fix all common cases.

**Comment by 23365209** [comment]
Yup, this has fixed it.
Thank you :)

(closing this issue)
