### ISSUE TITLE
"Prefer current selection" option under Selection Info not working as intended

### ISSUE THREAD

**Issue by bananabreaddd** [fooyin/fooyin#247]
**Bug Description**
When navigating to Settings -> Interface and selecting "Prefer current selection" under Selection Info, instead of preferring the current selection, the currently playing track is still preferred. This issue started appearing after updating to version 0.6.0 or 0.6.1; it was functioning correctly in version 0.5.3. I opened a playlist, played a song, and used my arrow keys & mouse to click up/down through my songs, but my Album Art/Selection viewer remained on the currently playing song.

**To Reproduce**
1. Go to Settings -> Interface.
2. Under Selection Info, select "Prefer current selection."
3. Attempt to see if the interface prefers the current selection or the currently playing track.

**Expected behaviour**
When "Prefer current selection" is chosen, the interface should prioritize the currently selected track rather than the currently playing track.

**System:**
 - OS: Fedora Linux 40, KDE Plasma 6.1.4
 - fooyin version: 0.6.1

**Additional context**
This issue persists after restarting fooyin, as well as after performing a clean flatpak install after clearing user data from ~/.var/app.

**Comment by ludouzi** [comment]
Hmm. I can't reproduce this on the current flatpak.

If you enable `Show track selection` on the status bar widget, does this update correctly when changing the selected track?

**Comment by bananabreaddd** [comment]
Interesting. Even with "Show track selection" enabled on the bottom bar the selected track is not preferred. Perhaps this only happens on a fresh install of 0.6.1?

 I just reinstalled fooyin after clearing ~/.var/app again, and ran into the same behavior. I've attached a recording of me on a fresh install of fooyin to hopefully show the issue more clearly.

https://github.com/user-attachments/assets/d7521609-ebe9-49c4-9d58-31b4650e298b

**Comment by ludouzi** [comment]
Thanks for the video - I think I see the problem now. 

The option under `Interface->Selection Info` is for the selection info widget. For the artwork panel, the equivalent setting is under `Interface->Artwork->Display`.

I'll see if I can make that a bit clearer in the settings.

**Comment by bananabreaddd** [comment]
Oh you're absolutely right that fixed the issue I was having. I appreciate your help and development 👍
