### ISSUE TITLE
Is it possible for the bitrate in the status widget to show a contantly updating value if the track has vbr?

### ISSUE THREAD

**Issue by OrangeRollo** [fooyin/fooyin#250]
As it stand %bitrate% in the status widget shows a single value even if the track has variable bit rate.  Is it possible to show a constantly updating value for bitrate if the track has vbr?

**Comment by ludouzi** [comment]
It's not currently possible, but it will simply be a case of querying the decoder for the bitrate while playing. I'll get around to adding that soon.
