### ISSUE TITLE
Possible Repeat Playlist Regression

### ISSUE THREAD

**Issue by Afurai** [fooyin/fooyin#252]
**Describe the bug**
Combining the "Repeat Playlist" and "Shuffle" options does not result in the desired behavior of shuffling throughout the current playlist indefinitely. Currently, Fooyin repeats the previous track over and over again, even when explicitly pressing the "Next Track" button. Leaving the playlist option set to "Default," the shuffle works as expected but only plays the tracks once, which I am trying to avoid with the "Repeat Playlist" option.

**To Reproduce**
- Have a playlist with songs in it
- Select the options "Repeat Playlist" and "Shuffle"
- Play a track
- Press "Next"
- The selected song should repeat from the beginning again _(it's expected to shuffle to a different track in the current playlist)_

**Expected behavior**
Like the previous versions, the playlist is supposed to indefinitely shuffle throughout the songs that are in the current playlist, forever without repeating tracks until all other songs are played first. Fooyin is behaving as if the program has the "Repeat Track" option enabled instead. _(I'm sorry if this doesn't make too much sense)_

**Screenshots**
N/A

**System:**
 - OS: **Fedora 40**
 - fooyin version: **0.6.1**; 0.5.3 did not have this issue

**Additional context**
N/A

**Comment by ludouzi** [comment]
Thanks for the report. This has already been fixed in the [v0.6.2](https://github.com/fooyin/fooyin/releases/tag/v0.6.2) release.
