### ISSUE TITLE
Difference between Script function abbr from Foobar2000 to fooyin

### ISSUE THREAD

**Issue by SigHunter** [fooyin/fooyin#253]
Hi and thank you very much for Fooyin!! 

I tried to convert my file operations scripts from Foobar2000 to fooyin and I noticed a difference in behavior with obscure tags. 

It boils down to: Foobar abbreviates something only after a whitespace, while fooyin does it also after german umlauts (and others), apostrophes and dashes (maybe more). 
Foobar also abbreviated dots or dashes, fooyin ignores them.

The question is, is this intentional, just new behavior or maybe a bug? 

A few real world examples, don't mind the weird titles but those exist:

```
$abbr(Gängel Gängel Gang) 
fooyin: GnGnG
Foobar: GGG
```
```
$abbr(Kettenwolf greint 13:11-18)
fooyin: Kg111
Foobar: Kg1
```
```
$abbr(Egon Erwin's Mongo-Mumu)
fooyin: EEsMM
Foobar: EEM
```
```
$abbr(...und über allem weht der Wind so kalt)
fooyin: ubawdWsk
Foobar: .üawdWsk
```
```
$abbr(¡Viva la Gloria!)
fooyin: VlG
Foobar: ¡lG
```
```
$abbr(¿Dónde están los ladrones?)
fooyin: Dnenll
Foobar: ¿ell
```
Weird one: 
```
$abbr(21 Guns)
fooyin: 2G
Foobar: 21G (why?)
```

Love the Script editor btw, makes it much easier to debug elaborate scripts. It only needs bracket highlighting to be perfect

**System:**
 - OS: Gentoo Linux
 - fooyin version: 0.6.2
 - QT version: 6.7.2

**Comment by ludouzi** [comment]
Thanks for those examples. I wouldn't call this a bug, but it's definitely not intentional and could use some improvement.

The `$abbr` function currently uses the following regex: `\b[\w]`. This matches the first character at the beginning of each word. The problem here is that `\w` is the equivalent of `[a-zA-Z0-9_]`, which only matches ASCII characters.

I'll look into matching unicode characters instead.

**Comment by SigHunter** [comment]
> Thanks for those examples. I wouldn't call this a bug, but it's definitely not intentional and could use some improvement.
> 
> The `$abbr` function currently uses the following regex: `\b[\w]`. This matches the first character at the beginning of each word. The problem here is that `\w` is the equivalent of `[a-zA-Z0-9_]`, which only matches ASCII characters.
> 
> Edit: Looks like we can enable unicode matching for `\w`
> 
> > QRegularExpression::UseUnicodePropertiesOption
> > The meaning of the \w, \d, etc., character classes, as well as the meaning of their counterparts (\W, \D, etc.), is changed from matching ASCII characters only to matching any character with the corresponding Unicode property. For instance, \d is changed to match any character with the Unicode Nd (decimal digit) property; \w to match any character with either the Unicode L (letter) or N (digit) property, plus underscore, and so on. This option corresponds to the /u modifier in Perl regular expressions.

cool!
btw, some random questions that arose: 
- is there already an equivalent to $ascii() or $ansi() in fooyin? 
- is it possible or planned to use $replace(str,search,replace) with an arbitrary number of arguments? like in fb2k $replace(%title%,replacethis,withthat,replacethistoo,withthattoo,alsothis,tothat)

**Comment by ludouzi** [comment]
Supporting arbitrary arguments for `$replace` will be pretty simple, so I'll do that in a bit.

There's no `$ascii` or `$ansi` equivalent yet. I'll see about those later.

**Comment by SigHunter** [comment]
I have [ccf45a3](https://github.com/fooyin/fooyin/commit/ccf45a3311cf0e2f2ba9fd97fa3075e7b1bca644) a spin and it looks good! Everything abbreviates as one would expect (more testing probably necessary and will follow)

one more thing I noticed, off topic, sorry: variables (mostly title and catalognumber) sometimes contain a directory separator like / on linux and in file operations scripts, this leads to a directory from this point. for the moment, I encapsulate everything with e.g. $replace(%title%,/,)
is this the way it will stay and replacing is logical or should the directory separators (depending on current platform) be caught and replaced in general? (on foobar windows a / or \ becomes a dash as far as I remember)

**Comment by ludouzi** [comment]
Looks like `$abbr` will need more adjustment.

Directory separators are replaced with `-` for rename operations. I'll see if they can also be replaced for the other operations.

**Comment by SigHunter** [comment]
Regarding $replace() with multiple substrings (noticed while renaming Ära Krâ):

there seems to be an issue with non ascii characters:
this works:
```
$replace(Ära Krâ,Ä,A)
= Ara Krâ
```
with multiple arguments, the special characters stop working (Ä not replaced anymore), but ascii continue to work
```
$replace(Ära Krâ,Ä,A,r,b)
= Äba Kbâ
```

**Comment by SigHunter** [comment]
haven't tested $ascii yet but the others work as expected. anyway, this issue was about $abbr which works nicely, now.
very cool, thanks for everything! looking forward when I can uninstall foobar with wine :-)
