### ISSUE TITLE
Can't access my ssd via  directory browser

### ISSUE THREAD

**Issue by netzstrand** [fooyin/fooyin#260]
**Describe the bug**
I have recently started using Fooyin as a Linux alternative to foobar2000, which I have relied on for over 15 years. I truly appreciate the effort you have put into developing this software, as it provides a much-needed solution for Linux users like myself who have large music libraries.

My music collection is substantial, with over 500 GB of files stored on an SSD that is mounted within my home directory. The files are carefully organized into folders, which has always allowed me to navigate and manage my music efficiently using the "By Folder Structure" view in foobar2000.

However, when attempting to scan this folder as a library in Fooyin, I encountered some difficulties. Specifically, the experience feels somewhat disorganized, and the "Directory Browser" does not allow me to access my SSD directly. Even when I manually enter the path (e.g., "/home/username/ssd2/Audio/"), I am unable to access the directory, which hinders my ability to manage my collection effectively.

I would greatly appreciate any assistance or suggestions you might have to resolve this issue. Your support in improving Fooyin is highly valued, and I look forward to your guidance on how to address this challenge.

Thank you so much and Best Refards,
Chris

**System:**
 - OS:  KDE Neon 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

 - fooyin version: 0.6.2

**Comment by ludouzi** [comment]
I can think of several issues that may cause this. Are you using the flatpak by any chance?

**Comment by netzstrand** [comment]
Yes, I do use the flatpak version.

**Comment by ludouzi** [comment]
In that case it's a permissions issue: https://docs.flatpak.org/en/latest/sandbox-permissions.html

 The flatpak only has access to `/run/media`, `~/Download` and `~/Music` by default. This can be changed using something like [Flatseal](https://github.com/tchx84/Flatseal), or by using the terminal:

`flatpak override org.fooyin.fooyin --filesystem=<filepath here>`
