### ISSUE TITLE
The seekbar is changing size when the number 4 comes up in the countdown timer

### ISSUE THREAD

**Issue by OrangeRollo** [fooyin/fooyin#277]
For certain fonts the number 4 is physically bigger or shifted left (i.e. Noto Sans which is the default for KDE on my distro). When the number 4 comes up in a time on the seekbar countdown on the left (i.e. -05:54) the seekbar gets smaller while the 4 is displayed

I've done an overlay to show this along with a zoomed in version. I've lined up other UI elements like the search bar and the writing in the "Track" column. You can see everything left of the 4 is shifted over.

![Size difference](https://github.com/user-attachments/assets/84279de1-a20f-427e-8d71-cbba3fe4862c)
![Size difference zoom](https://github.com/user-attachments/assets/adb04b73-528b-4644-9b43-7f7a74d8ec81)

I got around this by setting the font to something different (Dejavu Sans but others work) but I expect something like Noto Sans will be the default for most users.

 - OS: EndeavourOS (6.10.10-arch1-1 x86_64)
 - fooyin version: 0.6.2

**Comment by ludouzi** [comment]
I wasn't able to reproduce this with the same font but https://github.com/fooyin/fooyin/commit/3d4374208f3e6a828360b5ddda4ea21c330429e0 may help.

**Comment by OrangeRollo** [comment]
[3d43742](https://github.com/fooyin/fooyin/commit/3d4374208f3e6a828360b5ddda4ea21c330429e0) appears to have fixed it for me. Thanks!
