### ISSUE TITLE
Flatpak package out of date

### ISSUE THREAD

**Issue by NotoriousNico** [fooyin/fooyin#278]
I've noticed that the Flatpak hosted on flathub.org is still on version 0.6.1.
Granted, version 0.7.0 was just released a few hours ago, but the Flatpak version also never got the update to version 0.6.2.

Since the .deb file doesn't come with its own update sources, I rather prefer to use fooyin as a Flatpak package.
But that only makes sense to me if it gets the same frequent updates as the .deb releases on GitHub.

**Comment by ludouzi** [comment]
The flatpak is actually on version 0.6.2; the metainfo wasn't updated last update.

Updating the flatpak package is done automatically by using [Anitya](https://release-monitoring.org/) to check for the latest version. There is usually a delay there as the GitHub API is rate limited, but it should be updated today.

**Comment by NotoriousNico** [comment]
Thank you for the quick reply.

I only discovered fooyin a few days ago and was just looking at the Flatpak's metadata. My bad!

But it's really good to know that it gets updated automatically. Will switch from .deb to Flatpak then, once the update is out there as well.
