### ISSUE TITLE
Random skipping of song when playing them

### ISSUE THREAD

**Issue by Kri-U** [fooyin/fooyin#282]
**Describe the bug**
Whem i'm playing flac files (maybe other but I did not caught that yet), the player is skipping to the next song after a very short white noise, this can happen anywhere in the song and I can replay the song at the point where it skipped before without problem.
The log talk about an ffmpeg error : Invalid data found when processing input
[log fooyin.txt](https://github.com/user-attachments/files/17085820/log.fooyin.txt)

**To Reproduce**
Play a flac file and sometimes it should skip

**Expected behaviour**
The file should always play seamlessly without random crash on reading

**System:**
 - OS: Opensuse TumbleWeed 20240919
 - fooyin version: 0.6.2 (waiting for 0.7.x to release on OpenSUSE)

**Additional context**
The last 72 lines of the log about kf.coreaddons showed when exporting the log as a txt, they were not there when looking at it in Fooyin
I'll add a file where the bug occured in case of the bug coming from here
[C418 - 2 years of failure - 08 house_loneliness.zip](https://github.com/user-attachments/files/17085825/C418.-.2.years.of.failure.-.08.house_loneliness.zip)

Also I'm pretty new to Fooyin, started using today so I could be missing something

**Comment by ludouzi** [comment]
I can't reproduce this on my Arch system so I'll do some testing in an OpenSUSE VM in a bit.

**Comment by ludouzi** [comment]
I can't reproduce this on a fresh install of openSUSE Tumbleweed. The error suggests it may be an ffmpeg issue though.

Can you post the output of `ffprobe <file>`? Does it play fine using `ffplay <file>`?

**Comment by Kri-U** [comment]
So I did a system update, tested the program several hours and the problems disappeared, probably a random bug, or a bug not from fooyin and resolved by the system update.
I'll close the issue.
Thanks for fooyin, love it !
