### ISSUE TITLE
File browser widget - allow widget to be horizontally scrolled.

### ISSUE THREAD

**Issue by f1refa11** [fooyin/fooyin#285]
In my player layout the file browser widget is small, so i can't see the files' extensions(.mp3 or .flac) without resizing the window. By allowing the widget to be horizontally scrolled i can quickly scroll the widget with Shift+Scroll.

**Comment by ludouzi** [comment]
Done with https://github.com/fooyin/fooyin/commit/a483e729abc6ab5235c5ec582c2dc05c092771c4.

Horizontal scrolling can be enabled by turning off `Elide text` in `Settings->Widgets->Directory Browser`.

**Comment by f1refa11** [comment]
Thank you very much! :heart:
