### ISSUE TITLE
Unable to play audio files from M3U playlist with Windows relative file paths

### ISSUE THREAD

**Issue by Ace4896** [fooyin/fooyin#289]
**Describe the bug**
When loading an M3U playlist that contains Windows relative file paths (e.g. `folder\song.opus`), any audio files referenced by these relative file paths cannot be played.

**To Reproduce**

- Create the following folder structure:
  ```
  .
  ├── folder
  │   └── song.opus
  ├── unix.m3u8
  └── windows.m3u8
  ```
- In `unix.m3u8`, add the following contents:
  ```
  folder/song.opus
  ```
- In `windows.m3u8`, add the following contents:
  ```
  folder\song.opus
  ```
- In fooyin, attempt to load each playlist. The playlist with Unix file separators loads fine, while the playlist with Windows file separators does not

**Expected behaviour**
Playlists that contain Windows relative file paths should load correctly

**Screenshots**
After importing the playlist with Windows relative file paths, the track properties look like this, which might give some clues:

![Track Properties](https://github.com/user-attachments/assets/462f70da-5b38-47f4-a11b-e5a3578d1c8c)

**System:**
 - OS: Fedora 40 KDE
 - fooyin version: 0.7.1 Flatpak

**Additional context**
My use case is sharing the same playlist files between Windows, Linux and Android. So far, I've been doing this with foobar2000, which exports M3U playlists using relative file paths with `\` as the separator. From my quick testing, foobar2000 seems to be able to load playlists with either `\` and `/`.

I can manually edit the exported playlists, but it would be nice if fooyin could handle both file separators.

**Comment by ludouzi** [comment]
This is actually a common problem for Linux software, as `\` is a valid character for filenames, which means replacing all of them with `/` may produce an invalid filepath.

I think the best way to handle this would be to first check if the file exists as is, and then replace all `\` with `/` and try that. If not, we can ignore that file.

**Comment by Ace4896** [comment]
Thanks for the quick fix! I just tried building the current master branch and I'm able to load my Windows exported playlists now.

Also, I wanted to say that fooyin is a great music player! I've been searching for a Linux foobar2000 clone for a long time, and fooyin is very, very close to what I need (just ReplayGain scanning, which I see is already in the works).
