### ISSUE TITLE
Translation related issues

### ISSUE THREAD

**Issue by CarterLi** [fooyin/fooyin#306]
## The display language of `OpenMPT  Settings` dialog is not changed even if its texts have been translated

While the translation works for Game Music Emu

![image](https://github.com/user-attachments/assets/bc7c4f00-e3d8-4296-bca3-720171a9fcd2)

https://github.com/fooyin/fooyin/blob/2d579fa1056733236bfacdbe7b9ebfbf8ffc7092/data/translations/fooyin_zh_CN.ts#L6290

**Comment by CarterLi** [comment]
The translation works for `Game Music Emu`

**Comment by CarterLi** [comment]
Some texts are not translatable. They doesn't exist in the `.ts` file

![image](https://github.com/user-attachments/assets/d41e53e2-df17-4b85-bc25-5c2b9cb9bae8)

**Comment by CarterLi** [comment]
@ludouzi What do you mean by `Library Selection Playlist` in Library Tree settings dialog?

![image](https://github.com/user-attachments/assets/f68e2499-bd5c-4265-b26a-75c311578386)

**Comment by CarterLi** [comment]
![image](https://github.com/user-attachments/assets/9d1dc535-705c-4c14-b23b-104143d0e065)

Tag Editor settings

**Comment by CarterLi** [comment]
For some reason, `Cut` `Copy` and `Paste` don't have `alt` shortcuts. After translated to Chinese the Edit menu looks kinda weird

![image](https://github.com/user-attachments/assets/399b3886-1821-4262-880d-5558a579c96a)

https://github.com/fooyin/fooyin/blob/2d579fa1056733236bfacdbe7b9ebfbf8ffc7092/src/gui/playlist/playlistwidget.cpp#L184-L187

Is it intentional?

**Comment by CarterLi** [comment]
Same as `Play` `Pause` ... in playback menu

![image](https://github.com/user-attachments/assets/658ebd69-87ed-4fdc-9756-7860079b8a05)

**Comment by CarterLi** [comment]
Some texts in Log dialog are not translatable

![image](https://github.com/user-attachments/assets/5fcbb6f1-04ce-4b7f-a2f0-ea143ba7cd94)

**Comment by CarterLi** [comment]
![image](https://github.com/user-attachments/assets/4207c601-f689-4376-b104-2d3f1be8768b)

Prests items are not translatable

**Comment by ludouzi** [comment]
Thanks for finding all those (currently) untranslatable strings. I'll handle those in a bit.

`Library Selection Playlist` refers to the automatic playlist that is created with the selected tracks when making/changing a selection. It could also be called `Library Viewer Playlist`.

The menubar actions not having alt shortcuts isn't intentional - I just haven't got around to adding them yet.

**Comment by CarterLi** [comment]
![image](https://github.com/user-attachments/assets/96009191-8852-46f2-87e8-0eb98e177c57)

Contextmenu

**Comment by CarterLi** [comment]
> the automatic playlist that is created with the selected tracks when making/changing a selection

Still didn't get it. Do you mean that whenever I select some tracks in the playlist, a temporary playlist will be created?

**Comment by ludouzi** [comment]
When making a selection in the library tree (such as selecting an album item), it will create a playlist with the selected tracks so they can be viewed as a playlist.

**Comment by CarterLi** [comment]
@ludouzi Do you need to regenerate `.ts` files after https://github.com/fooyin/fooyin/commit/59f38529ce8f71da5efa2014603a1baa920c042c?

**Comment by ludouzi** [comment]
Yeah. Existing changes in the Weblate repo need to be merged before then to avoid conflicts. I'll do so in a bit.

**Comment by CarterLi** [comment]
Some texts in tag editor settings are still not translatable

![image](https://github.com/user-attachments/assets/747dd300-1066-4b25-8627-47dcff8d6b9b)

**Comment by ludouzi** [comment]
That's because before https://github.com/fooyin/fooyin/commit/98185786373d96a28e652790e6aadb10415c678c, the fields were saved (including the current names) on close. Does resetting the page fix it?

**Comment by CarterLi** [comment]
I think most issues have been resolved. Closing
