### ISSUE TITLE
Use $XDG_STATE_HOME instead of $XDG_CONFIG_HOME for storing state

### ISSUE THREAD

**Issue by yuki0iq** [fooyin/fooyin#312]
According to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/),
> The `$XDG_STATE_HOME` contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in `$XDG_DATA_HOME`. It may contain:
> - actions history (logs, history, recently used files, …)
> - current state of the application that can be reused on a restart (view, layout, open files, undo history, …)

`[Player]/ActivePlaylistIndex` and `[Interface]/SettingsDialogSize` are some examples of the keys from config file that probably should be placed in `$XDG_STATE_HOME`

**Comment by ludouzi** [comment]
This will require some breaking changes and a major refactoring of the settings manager, but I'll see what I can do.

**Comment by ludouzi** [comment]
Turns out this was easier than expected. I also moved the version setting to the database as it doesn't make sense in a configuration file.
