### ISSUE TITLE
Quit does not work when minimized to systray and some minor stuff

### ISSUE THREAD

**Issue by SigHunter** [fooyin/fooyin#323]
**Hi, minor thing I noticed:**
I have enabled "show systray icon" in settings and right clicking and choosing "Quit" on tray icon does not work when there is no fooyin window besides the tray icon. when there is also a task bar element/window additionally to the tray, "Quit" works.

**Reproduce with this:**
Enable "show systray icon", 
left click on tray icon to minimize fooyin to systray only, 
right click the tray icon and choose "Quit". 
Nothing happens. 

As stated, Quit works when there is also a fooyin window in window bar. 

**System:**
 - OS: Gentoo Linux x64
 - fooyin version: 5c16455bda1914a60d61f1d1c0ba5ad710d7d01f
- QT 6.7.3
- KDE Plasma 6.2.0

Unrelated but probably not worthy of a separate bug report because I think it is not official yet:
%Tool% currently does not show flac encoders, it only shows e.g. LAME3.90. With same music collection in fooyin and Foobar2000, fb additionally shows for my collection: 
- reference libFLAC $version
- Xiph.Org libVorbis $version
- AO; aoTuV $version

thanks and keep up the good work!

**Comment by ludouzi** [comment]
Yeah, the encoding information is only read for mpeg files currently if they have a Xing header. I'll extend that to XiphComment based files later.

**Comment by SigHunter** [comment]
can confirm "Quit" from tray now works! tyvm
tested with 810609357a6db3ab05b16a52e6d8b6f59eb1f4b1
