### ISSUE TITLE
Arrow keys should change track based off currently selected search result

### ISSUE THREAD

**Issue by lstrsrt** [fooyin/fooyin#324]
I couldn't find a way to implement this so I'll just open an issue. Right now when you make a search, it jumps to the first matching result (or to the result clicked on in the search popup), so after that I would expect the arrow keys to select the next/previous track. But instead the keys still switch from the _previously_ (before the search) selected song.

https://github.com/user-attachments/assets/9e58c609-18fd-4ebc-88db-353bf68ede85

When multiple search results are selected I guess it makes sense to base it off the first result.

**Comment by ludouzi** [comment]
This is because the arrow keys operate from the current index rather than the selected index - it just so happens that the current index becomes selected when changed. Fix should be as simple as marking the first result the current index.
