### ISSUE TITLE
Question: disable libvgm option?

### ISSUE THREAD

**Issue by AngryPhantom** [fooyin/fooyin#330]
Hello,
First of all, thank you for this nice player.
The question is: how do I disable libvgm in the compile options? I want to get rid of this libvgm-player-git package which is in the AUR and which gives me some pain.
Can it be disabled?

Thank you in advance.

**Comment by ludouzi** [comment]
Thank you.

The libvgm plugin can be disabled by passing `-DBUILD_LIBVGM=OFF` to CMake in the configure/build stage. It will also be skipped if this repo was cloned without submodules and the system library can't be found.

**Comment by AngryPhantom** [comment]
Thank you very much! Sorry, I should've read the BUILD.md in your source files. My bad.
