### ISSUE TITLE
Status bar track selection info doesn't disappear when nothing is selected

### ISSUE THREAD

**Issue by miged** [fooyin/fooyin#331]
**Describe the bug**
I noticed a slight regression where the track selection info in the status bar doesn't go blank anymore, instead it now shows zeroes when nothing is selected.

**To Reproduce**
1. Enable track selection info in status bar
2. Make sure nothing is selected

**Expected behaviour**
Right side of the status bar should be blank.

**System:**
 - OS: Fedora 40
 - fooyin version: 0.8.1 (flatpak)

**Comment by ludouzi** [comment]
Thanks for noticing that. You can also fix it yourself by wrapping the selection script in a conditional. Default is now:

`[%trackcount% $ifequal(%trackcount%,1,Track,Tracks) | %playtime%]`
