### ISSUE TITLE
When multiple albums are present in the same playlist, only the first one's album art will be shown

### ISSUE THREAD

**Issue by giantplaceholder** [fooyin/fooyin#335]
**Describe the bug**
The playlist UI module allows to show album art in a separate column, much like DeaDBeeF does.

Unfortunately, when multiple albums (per their ID tags) are present in the same playlist, only one album art will be shown - that of the first track's album.

I honestly tried to find the appropriate UI setting, but did not find it.

**To Reproduce**
* Add one or multiple tracks from the same album, per their meta.
* Add one or multiple tracks from another album.

**Expected behaviour**
* Multiple album artworks will be shown in a playlist when multiple albums are added in the same playlist.

**Screenshots**
![image](https://github.com/user-attachments/assets/c637ec9b-2dff-45db-a54d-85874af4bf25)

**System:**
 - OS: Arch (rolling)
 - fooyin version: 0.8.1

**Additional context**
This is how the same situation is handled in DeaDBeeF:

![image](https://github.com/user-attachments/assets/36e96468-efd2-41b4-ac66-2639550d1739)

**Comment by ludouzi** [comment]
You will need to change the playlist preset in the right click context menu so the tracks are grouped by album.

The default preset lists the tracks in a table format and as there's nothing to group by, it can only show the artwork of the first track.

**Comment by ludouzi** [comment]
I'll see if I can think of a more descriptive title, though it contains much more than just grouping settings. It also contains fonts, colours and various other options for the headers/subheaders and it's scripts.
