### ISSUE TITLE
Doesn't install, "libicu" is newer on Kubuntu 24.10 Oracular Oriole

### ISSUE THREAD

**Issue by mwwdh** [fooyin/fooyin#345]
**Describe the bug**
fooyin doesn't install on the latest Kubuntu 24.10 release because of an unsatisfied dependence of "libicu72". The installed version is "74"

**System:**
 - OS: Kubuntu 24.10 Oracular Oriole
 - fooyin version: 0.8.1-oracular_amd64.deb

**Additional context**
```
fooyin : Depends: libicu72 but it is not installable
...
libicu74/oracular,now 74.2-1ubuntu4 amd64 [installed,automatic]
```

**Comment by ludouzi** [comment]
Thanks for heads up. This most likely affects Noble as well.
