### ISSUE TITLE
Supporting application/octet-stream mime pollutes application list of kde.

### ISSUE THREAD

**Issue by arenekosreal** [fooyin/fooyin#349]
**Describe the bug**
Fooyin exists in all mime types' supported applications list.

**To Reproduce**
1. Build and install fooyin.
2. Update mime database by running `update-desktop-database`
3. Open KDE's System Setting app, go to `Default Applications` -> `File Associations` and check `Known Types`

**Expected behaviour**
All mime types has its correct associations. For example, `application/gzip` should not contain fooyin.

**Screenshots**
![image](https://github.com/user-attachments/assets/643fce09-37ff-4f1b-b2b4-f85997ead7c2)

**System:**
 - OS: Arch Linux with KDE
 - fooyin version: 0.8.1

**Additional context**
It seems that it is [here](https://github.com/fooyin/fooyin/blob/master/src/plugins/rawaudio/CMakeLists.txt#L11) add a `application/octet-stream` mime support and causes the problem. A workaround is editing fooyin's desktop file, removing it from `MimeType` and updating mime database.

**Comment by bassstorm** [comment]
Noticed the same on Debian 12 (flatpak install).

**Comment by ludouzi** [comment]
That mime was added to support opening .bin files. But as not every bin file is audio, and that type is used for a lot of other formats, I'll remove it.
