### ISSUE TITLE
[Feature Request] A small but big search enhancement

### ISSUE THREAD

**Issue by Tea-Fox** [fooyin/fooyin#350]
I use fooyin as my main music player on my laptop, however the search it uses seems to only highlight the items in a Playlist, not bring them all together into view by temporarily hiding/trimming the unrelated items away (iTunes does it this way for example).
If you search for, just as an example, "XYZ", then only the tracks that contain "XYZ" somewhere (in the Album name, Artist name, Track name, etc.) will appear while every other track that doesn't contain "XYZ" is hidden away until you delete the search term from the search field or search for something else. Basicaly it cuts down on scrolling a lot and makes things simpler to search for.

It is a bit difficult to describe, but what I mean is hopefully understandable.

So, I would like to request this as an option for a future release of fooyin.

**Comment by ludouzi** [comment]
Thanks for the request.

I agree that this would be a big improvement. A potential issue is performance in large playlists, but I'll see what I can do.
