### ISSUE TITLE
Listenbrainz integration broken

### ISSUE THREAD

**Issue by MegaAppster** [fooyin/fooyin#354]
**Describe the bug**
When adding a LB account it states Logged In however if you play a track and it attempts to scrobble it will go back to showing that you're not logged in. Logs also show "Provided Authorization header is invalid"
`fy.scanner: Scan of "Music" took "0:00.105000"
fy.scrobbler: Sending request "album=Rodeo&albumArtist=Travis Scott&api_key=b2d57c978a22be279cc3be6d67627fea&artist=Travis Scott, Swae Lee, Chief Keef&lang=en&method=track.updateNowPlaying&sk=uVnnkI9KcmUIFI_Fohd1fwEvOHi-LcEA&track=Nightcrawler&api_sig=c54bd44846c10ec1b8ba1f1b223f025b&format=json"
fy.engine: Loading track: "1-07 - Nightcrawler (feat. Swae Lee & Chief Keef).flac"
fy.engine: Track status changed: "Loading"
fy.engine: Track status changed: "Loaded"
fy.engine: Track status changed: "Buffered"
fy.engine: State changed: "Playing"
qt.network.http2: stream 1 finished with error: "Host requires authentication"
fy.scrobbler: "Provided Authorization header is invalid. (401)"
fy.scrobbler: "Submitting scrobbles (LastFM)"
fy.scrobbler: Sending request "albumArtist[0]=Travis Scott&album[0]=Rodeo&api_key=b2d57c978a22be279cc3be6d67627fea&artist[0]=Travis Scott\u001FSwae Lee\u001FChief Keef&duration[0]=321&lang=en&method=track.scrobble&sk=uVnnkI9KcmUIFI_Fohd1fwEvOHi-LcEA&timestamp[0]=1729518652&trackNumber[0]=7&track[0]=Nightcrawler&api_sig=238096cb1f027498434c0a517fd44354&format=json"
fy.scrobbler: Scrobbles accepted: 1
fy.scrobbler: Scrobbles ignored: 0
fy.scrobbler: Scrobble accepted: "Nightcrawler"`

**To Reproduce**
Attempt to login to LB

**Expected behaviour**
Successful log in

**System:**
 - OS: Arch Linux, Zen kernel, Plasma
 - fooyin version: 0.8.1

**Comment by ludouzi** [comment]
Are you inputting your user token? I can reproduce this if I try logging in without a user token.

**Comment by MegaAppster** [comment]
My bad, I was under the impression it was either or, I didn't realize you needed both

**Comment by ludouzi** [comment]
Yeah, it was a little confusing. With https://github.com/fooyin/fooyin/commit/f5579286c3035036337e52d44da945525f4bf2b0 the login button will be disabled until the token is entered which should make things clearer.
