### ISSUE TITLE
Ability to change update rate for bitrate in the status bar

### ISSUE THREAD

**Issue by iamalexei** [fooyin/fooyin#375]
Currently, when a VBR track is played, bitrate in the status bar changes a bit to fast. Please, add ability to change the update rate for the bitrate value, e.g. once per second, once per 3 seconds, once per 5 seconds, and once per 10 seconds.

**Comment by ludouzi** [comment]
Good idea. The timer which updates the bitrate is currently set to run every 200ms. I'll make that number configurable.

**Comment by iamalexei** [comment]
@ludouzi thank you!
