### ISSUE TITLE
Cue+ape trouble

### ISSUE THREAD

**Issue by Pathologic** [fooyin/fooyin#376]
**Describe the bug**
When playing an cue+ape image album, after moving to the next track, the sound disappears until the end of the track.

**To Reproduce**
Add cue+ape image album to the playlist and start playback. When track 1 is finished, track 2 starts to play and the sound disappears.

**Expected behaviour**
Smooth playback.

**System:**
 - OS: Kubuntu 24.04.1 LTS x86_64
 - fooyin version: 0.8.1

**Comment by Pathologic** [comment]
I've checked again and found out that flac and wavpack are affected too.

**Comment by ludouzi** [comment]
https://github.com/fooyin/fooyin/commit/7cf955ffb5639a47a00f43afed065e40ee606c71 fixes a related issue for some decoders. I'll do some testing of APE and CUE in a bit.

**Comment by ludouzi** [comment]
Should now be fixed with https://github.com/fooyin/fooyin/commit/64329eb858795f08d9ec5be2c216ac158ef415a2.

**Comment by Pathologic** [comment]
Seems to be fixed, thank you.

**Comment by Pathologic** [comment]
Some more fixes needed. Now I get the silence when moving to the next album in playlist.
