### ISSUE TITLE
Mono audio causes crash with waveform seekbar

### ISSUE THREAD

**Issue by vic-bay** [fooyin/fooyin#383]
**Describe the bug**
If you have mono audio playing in fooyin, it will crash as soon as the player tries to draw a waveform seekbar. It crashes either if you bring up minimised player with the seekbar already added, or add a waveform seekbar to the layout as the audio is played.

**To Reproduce**
1. Play a mono channel audio.
2. Add waveform seekbar.
3. It will crash.

**Expected behaviour**
Mono channel waveform seekbar on display.

**Screenshots**

**System:**
 - OS: Arch Linux
 - fooyin version: Version: 0.8.1
Based on Qt 6.8.0 (GCC 14.2.1 20240910, x86_64)

**Additional context**
An example track that crashes the player is attached.

[dance.zip](https://github.com/user-attachments/files/17672041/dance.zip)

**Comment by ludouzi** [comment]
Thanks. I can reproduce this if the downmix option is set to stereo.
