### ISSUE TITLE
[Feature Request] Allow Mouse Buttons to be Used as Shortcuts

### ISSUE THREAD

**Issue by c0d3g0r3** [fooyin/fooyin#91]
I have keys on my mouse which would make changing song while doing other tasks a breeze, so I feel it'd work well to allow them to be used.

**Comment by ludouzi** [comment]
QAction only accepts a QKeySequence for setting action shortcuts, so only keyboard keys are supported. It would take a lot of work to manually add support.

As fooyin has support for MPRIS, and if you're just looking to use mouse buttons for playback control (play/pause/next etc), then you should be able to assign mouse buttons to something like playerctl.

**Comment by ludouzi** [comment]
Closing this issue as I do not have the time to implement it. As mentioned earlier, there are ways to assign mouse buttons to playerctl to control playback globally.
